[package]
name = "rust_snuba"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["rust_arroyo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "querylog_consumer"
path = "src/bin/consumer/querylog_consumer.rs"

[dependencies]
rust_arroyo = { path = "./rust_arroyo" }
tokio = { version = "1.19.2", features = ["full"] }
rdkafka = { version = "0.28", features = ["cmake-build"] }
futures = "0.3.21"
serde_json = "1.0.81"
serde = {version = "1.0.137", features = ["derive"] }
serde_yaml = "0.9"
