[package]
name = "rust_snuba"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["rust_arroyo"]

[dependencies]
rust_arroyo = { path = "./rust_arroyo" }
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
