name: ci
on:
  pull_request:

jobs:
  post_changes:
    name: Post new DDL changes from migrations
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        name: Checkout master for diffing
        ref: master
      - uses: actions/checkout@v3
        name: Checkout HEAD of code that may have migration changes
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install-python-dependencies
      - name: Run the migration script
        run: |
          python scripts/ddl-changes.py
