name: ci
on:
  pull_request:

jobs:
  post_changes:
    name: Post new DDL changes from migrations
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install-python-dependencies
      - name: Run the migration script
        run: |
          python scripts/ddl_changes.py
